import BarChart from '../../components/charts/BarChart'
import LineChart from '../../components/charts/LineChart'
import { revenueData, userGrowthData } from '../../data/mockData'

const sprintData     = [
  { label: 'Jun', value: 4 },  { label: 'Jul', value: 8 },
  { label: 'Aug', value: 12 }, { label: 'Sep', value: 10 },
  { label: 'Oct', value: 16 }, { label: 'Nov', value: 21 },
]

const matchSuccessData = [
  { label: 'Jun', value: 62 }, { label: 'Jul', value: 68 },
  { label: 'Aug', value: 71 }, { label: 'Sep', value: 74 },
  { label: 'Oct', value: 78 }, { label: 'Nov', value: 82 },
]

const kpis = [
  { label: 'Match Success Rate', value: '82%', change: '+4%',  color: '#16a34a' },
  { label: 'Sprint Completion',  value: '67%', change: '+9%',  color: '#2563eb' },
  { label: 'User Retention',     value: '74%', change: '+3%',  color: '#982598' },
  { label: 'Marketplace GMV',    value: '$8.9K', change: '+18%', color: '#d97706' },
]

export default function ReportsModule() {
  return (
    <div className="space-y-5">
      <div>
        <h2 className="text-lg font-extrabold" style={{ color: '#15173D' }}>Reports & Analytics</h2>
        <p className="text-xs text-gray-400 mt-0.5">Platform-wide KPIs and trend reports</p>
      </div>

      {/* KPI row */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {kpis.map(k => (
          <div key={k.label} className="bg-white border border-gray-100 rounded-2xl p-5">
            <div className="text-2xl font-extrabold mb-0.5" style={{ color: k.color }}>{k.value}</div>
            <div className="text-xs text-gray-400 mb-1">{k.label}</div>
            <div className="text-xs font-semibold text-green-600">{k.change} vs last month</div>
          </div>
        ))}
      </div>

      {/* Charts grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        <div className="bg-white border border-gray-100 rounded-2xl p-5">
          <h3 className="text-sm font-bold mb-1" style={{ color: '#15173D' }}>User Growth</h3>
          <p className="text-xs text-gray-400 mb-4">Registered users over time</p>
          <LineChart data={userGrowthData.map(d => ({ label: d.month, value: d.users }))} color="#15173D" />
        </div>

        <div className="bg-white border border-gray-100 rounded-2xl p-5">
          <h3 className="text-sm font-bold mb-1" style={{ color: '#15173D' }}>Revenue Trend</h3>
          <p className="text-xs text-gray-400 mb-4">Monthly revenue ($)</p>
          <LineChart data={revenueData.map(d => ({ label: d.month, value: d.revenue }))} color="#982598" />
        </div>

        <div className="bg-white border border-gray-100 rounded-2xl p-5">
          <h3 className="text-sm font-bold mb-1" style={{ color: '#15173D' }}>Active Sprints</h3>
          <p className="text-xs text-gray-400 mb-4">New sprints started per month</p>
          <BarChart data={sprintData} color="#2563eb" />
        </div>

        <div className="bg-white border border-gray-100 rounded-2xl p-5">
          <h3 className="text-sm font-bold mb-1" style={{ color: '#15173D' }}>Match Success Rate (%)</h3>
          <p className="text-xs text-gray-400 mb-4">% of matches progressing to sprints</p>
          <LineChart data={matchSuccessData} color="#16a34a" />
        </div>
      </div>

      {/* Founder matches per month */}
      <div className="bg-white border border-gray-100 rounded-2xl p-5">
        <h3 className="text-sm font-bold mb-1" style={{ color: '#15173D' }}>Founder Matches per Month</h3>
        <p className="text-xs text-gray-400 mb-4">Total matches generated by the AI engine</p>
        <BarChart
          data={revenueData.map(d => ({ label: d.month, value: d.matches }))}
          color="#982598" color2="#e8d4e8"
          label="Matches" label2="Avg Score"
          height={180}
        />
      </div>
    </div>
  )
}
